steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/emely-gcp/emelybackend:$SHORT_SHA",
        '--build-args="HUGGINGFACE_KEY=$_HUGGINGFACE_KEY"',
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/emely-gcp/emelybackend:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "emely-backend-develop",
        "--image=gcr.io/emely-gcp/emelybackend:$SHORT_SHA",
        "--platform=managed",
        "--region=europe-west3",
        "--allow-unauthenticated",
        "--memory=256Mi",
        "--max-instances=2",
      ]
timeout: "1200s"
