steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/emelybrainapi/github.com/nordaxon/emelys_brain:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/emelybrainapi/github.com/nordaxon/emelys_brain:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'emely-chat-service-api-staging', '--region=europe-west1', '--platform=managed',
         '--image=eu.gcr.io/emelybrainapi/github.com/nordaxon/emelys_brain:$SHORT_SHA']

