steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        'docker build --build-arg="huggingface_key=$_HUGGINGFACE_KEY" --build-arg="use_huggingface_fika=$_USE_HUGGINGFACE_FIKA" -t gcr.io/emely-gcp/emelybackend:$SHORT_SHA .',
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/emely-gcp/emelybackend:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_SERVICE_NAME",
        "--image=gcr.io/emely-gcp/emelybackend:$SHORT_SHA",
        "--platform=$_PLATFORM",
        "--region=$_DEPLOY_REGION",
        "--allow-unauthenticated",
        "--memory=$_MEMORY",
        "--max-instances=$_MAX_INSTANCES",
        "--cpu=$_CPUS",
      ]
timeout: "1200s"
