steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'docker build --build-arg="huggingface_key=$_HUGGINGFACE_KEY" --build-arg="use_huggingface_fika=$_USE_HUGGINGFACE_FIKA" -t gcr.io/emely-gcp/emelybackend:$SHORT_SHA .',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/emely-gcp/emelybackend:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'emely-backend-develop',
        '--image=gcr.io/emely-gcp/emelybackend:$SHORT_SHA',
        '--platform=managed',
        '--region=europe-west3',
        '--allow-unauthenticated',
        '--memory=256Mi',
        '--max-instances=2',
      ]
timeout: '1200s'
